import pymem
import struct
import psutil
import time
import keyboard
import pyautogui
# ➤ Çalışan işlemlerden SonOyuncu Client'in adını bul
def find_process(name_part):
    for process in psutil.process_iter(['pid', 'name']):
        if name_part.lower() in process.info['name'].lower():
            return process.info['name']
    return None

# ➤ SonOyuncu Client'i bul
MC_ADDRESS = find_process("SonOyuncu")  # Süreç ismini buradan buluyor

if MC_ADDRESS is None:
    raise Exception("SonOyuncu Client çalışmıyor veya işlem adı yanlış!")

# ➤ Cheat Engine’den çektiğin adresler
X_ADDRESS = 0xBF946788  # X için adres
Y_ADDRESS = 0xBF946790  # Y için adres

# ➤ Minecraft sürecine bağlan
pm = pymem.Pymem(MC_ADDRESS)

# ➤ Belleğe float yazma fonksiyonu
def write_float(address, value):
    pm.write_bytes(address, struct.pack('f', value), 4)

# ➤ movefacing(x, y) fonksiyonu (Direkt Değer Yazma)
def facing_trigger(x, y):
    write_float(X_ADDRESS, float(x))
    write_float(Y_ADDRESS, float(y))
    print(f"X: {x}, Y: {y} olarak ayarlandı.")

def karpuzz():
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()


def kabakk():
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()

# ➤ Örnek kullanım: X = 30, Y = 90 olarak ayarlasın

def refreshenv():
    time.sleep(2)
    pyautogui.press('e')
    time.sleep(1)
    deniz_feneri()
    kabak_tohumu()
    karpuz_tohumu()
    toprak()
    pistona()
    pyautogui.press('esc')
    time.sleep(2)

def pistona():
    time.sleep(0.5)
    pyautogui.moveTo(815, 659)
    pyautogui.doubleClick()
    pyautogui.click()
    print("Piston'a çift tıklandı.")
    time.sleep(0.5)

def toprak():
    time.sleep(0.5)
    pyautogui.moveTo(851, 659)
    pyautogui.doubleClick()
    pyautogui.click()
    print("Toprak'a çift tıklandı.")
    time.sleep(0.5)

def deniz_feneri():
    time.sleep(0.5)
    pyautogui.moveTo(887, 658)
    pyautogui.doubleClick()
    pyautogui.click()
    print("Deniz Feneri'ne çift tıklandı.")
    time.sleep(0.5)

def karpuz_tohumu():
    time.sleep(0.5)
    pyautogui.moveTo(961, 664)
    pyautogui.doubleClick()
    pyautogui.click()
    print("Karpuz Tohumu'na çift tıklandı.")
    time.sleep(0.5)

def kabak_tohumu():
    time.sleep(0.5)
    pyautogui.moveTo(998, 663)
    pyautogui.doubleClick()
    pyautogui.click()
    print("Kabak Tohumu'na çift tıklandı.")
    time.sleep(0.5)

def bot():
    time.sleep(2)
    facing_trigger(170.3, 22.2)
    pyautogui.press('2')
    pyautogui.rightClick()
    facing_trigger(164.3, 34.8)
    pyautogui.rightClick()
    facing_trigger(90, 60)
    pyautogui.rightClick()
    facing_trigger(0, 60)
    pyautogui.rightClick()
    facing_trigger(-79.2, 35.7)
    pyautogui.rightClick()
    facing_trigger(-84.8, 22.7)
    pyautogui.rightClick()
    facing_trigger(-83.4, 9.7)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    facing_trigger(-76, 16.6)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    facing_trigger(0, 50)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    facing_trigger(90, 50)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    facing_trigger(157.3, 18.1)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    facing_trigger(168.4, 9.4)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    facing_trigger(169.3, 6.6)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(160.4, 12)
    pyautogui.rightClick()
    facing_trigger(100.3, 32.3)
    pyautogui.rightClick()
    facing_trigger(-10.7, 32.6)
    pyautogui.rightClick()
    facing_trigger(-71.3, 12)
    pyautogui.rightClick()
    facing_trigger(-79.3, 6.6)
    pyautogui.rightClick()
    facing_trigger(-90.6, 22.6)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    facing_trigger(-90.6, 36.2)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-90.6, 25.9)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    facing_trigger(-90.6, 37.9)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-90.6, 33.1)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    facing_trigger(65.9, 33.8)
    pyautogui.rightClick()
    facing_trigger(-2.1, 62.5)
    pyautogui.rightClick()
    facing_trigger(-172.8, 23.1)
    pyautogui.rightClick()
    facing_trigger(-170.5, 36.7)
    pyautogui.rightClick()
    facing_trigger(69, 15.9)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    facing_trigger(0, 37.9)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    facing_trigger(-90, 38.7)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    facing_trigger(-159.5, 15.9)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    facing_trigger(-170.3, 9.7)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    facing_trigger(-169.8, 6.7)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-160.4, 12.2)
    pyautogui.rightClick()
    facing_trigger(-96.2, 32.1)
    pyautogui.rightClick()
    facing_trigger(15.8, 30.6)
    pyautogui.rightClick()
    facing_trigger(69.1, 11.7)
    pyautogui.rightClick()
    facing_trigger(179.3, 23.2)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    facing_trigger(179.6, 41.5)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(179.6, 25.3)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    facing_trigger(179.6, 59.6)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(179.6, 31)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    facing_trigger(-22.5, 38.7)
    pyautogui.rightClick()
    facing_trigger(-90.8, 66)
    pyautogui.rightClick()
    facing_trigger(97, 22.8)
    pyautogui.rightClick()
    facing_trigger(101, 34.6)
    pyautogui.rightClick()
    facing_trigger(-19.8, 17.2)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    facing_trigger(-90.8, 37.3)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    facing_trigger(180, 38.6)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    facing_trigger(106.9, 17)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    facing_trigger(100.3, 9.5)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    facing_trigger(100.8, 6.7)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(110, 12.4)
    pyautogui.rightClick()
    facing_trigger(171.2, 30.8)
    pyautogui.rightClick()
    facing_trigger(-76, 29.8)
    pyautogui.rightClick()
    facing_trigger(-21, 12.2)
    pyautogui.rightClick()
    facing_trigger(89.7, 22.1)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    facing_trigger(89.7, 35.3)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(89.7, 23.3)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    facing_trigger(89.7, 40)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(89.7, 29.3)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    facing_trigger(-116.4, 34.5)
    pyautogui.rightClick()
    facing_trigger(180, 60)
    pyautogui.rightClick()
    facing_trigger(21.4, 34.3)
    pyautogui.rightClick()
    facing_trigger(19.5, 17.6)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    facing_trigger(90, 35)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('6')
    pyautogui.rightClick()
    facing_trigger(180, 34.4)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    facing_trigger(-112.4, 16.3)
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    pyautogui.press('4')
    pyautogui.rightClick()
    pyautogui.press('5')
    pyautogui.rightClick()
    facing_trigger(-111.6, 11.9)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-170.9, 29.9)
    pyautogui.rightClick()
    facing_trigger(20.3, 12.4)
    pyautogui.rightClick()
    facing_trigger(80, 30.4)
    pyautogui.rightClick() 
    facing_trigger(-45, 0)
    pyautogui.keyDown('w')
    time.sleep(4)
    pyautogui.keyUp('w')
    facing_trigger(179.8, 29.7)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(90, 30)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.8)
    pyautogui.keyUp('w')
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-50.1, -13.2)
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-42.3, -14.9)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-20.8, -20.9)
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-52, -17.9)
    pyautogui.press('1')
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-36.4, -25.5)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-74.2, -18.8)
    pyautogui.press('3')
    pyautogui.rightClick()
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-72.3, -38.9)
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-180, 25.3)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(1.2)
    pyautogui.keyUp('w')
    facing_trigger(-180, 44)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-43.8, -13.3)
    pyautogui.press('1')
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-48, -13.5)
    pyautogui.rightClick()
    facing_trigger(-19.6, -18.1)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-54.9, -17.2)
    pyautogui.rightClick()
    facing_trigger(-70.5, -17.7)
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-41.7, -26.7)
    pyautogui.rightClick()
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-179.7, 1.5)
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    refreshenv()
    facing_trigger(-44.2, -15.7)
    pyautogui.press('3')
    pyautogui.rightClick()
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-48, -15.6)
    pyautogui.rightClick()
    facing_trigger(-70, -18)
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-63.7, -18.1)
    pyautogui.rightClick()
    facing_trigger(-19.5, -18.9)
    pyautogui.rightClick()
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-51.6, -33.1)
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(89.9, 24.8)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    facing_trigger(89.9, 44)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(0.1, 23.3)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    facing_trigger(0.1, 31.4)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(0.1, 25.5)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    facing_trigger(0.1, 30.6)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-179.8, 54.5)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-51.1, -15)
    pyautogui.press('1')
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-40.5, -15.9)
    pyautogui.rightClick()
    facing_trigger(-20, -19.8)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-64.6, -20.2)
    pyautogui.rightClick()
    facing_trigger(-89.1, -21)
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(0, -24.9)
    pyautogui.rightClick()
    facing_trigger(0, -41.7)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-179.7, 25.3)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    facing_trigger(-179.7, 40)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-51, -15.6)
    pyautogui.press('3')
    pyautogui.rightClick()
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-39.1, -14.4)
    pyautogui.rightClick()
    facing_trigger(-17.2, -17.6)
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-60.3, -20.1)
    pyautogui.rightClick()
    facing_trigger(-79.6, -19.8)
    pyautogui.rightClick()
    facing_trigger(-79.6, -19.8)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-40, -29.2)
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(135, 0)
    pyautogui.keyDown('w')
    time.sleep(2)
    pyautogui.keyUp('w')
    facing_trigger(-88.3, 21.9)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    facing_trigger(-88.3, 47.7)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-45.4, -14.7)
    pyautogui.press('1')
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-31.3, -16.2)
    pyautogui.rightClick()
    facing_trigger(-9, -18.2)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-56.8, -23)
    pyautogui.rightClick()
    facing_trigger(-88.6, -19.4)
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-21.1, -40.2)
    pyautogui.rightClick()
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(89.7, 0.1)
    pyautogui.keyDown('w')
    time.sleep(1.7)
    pyautogui.keyUp('w')
    facing_trigger(0, 0)
    pyautogui.keyDown('w')
    time.sleep(4)
    pyautogui.keyUp('w')
    facing_trigger(-179.9, 28.7)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-52.7, -14.3)
    pyautogui.press('3')
    pyautogui.rightClick()
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-41.3, -15.6)
    pyautogui.rightClick()
    facing_trigger(-72.6, -22.2)
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-60.3, -21.3)
    pyautogui.rightClick()
    facing_trigger(-19.8, -23)
    pyautogui.rightClick()
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-78.2, -21.5)
    pyautogui.rightClick()
    facing_trigger(-90.4, -41)
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-179.9, 23.2)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    facing_trigger(-179.9, 36.8)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-53.2, -13.7)
    pyautogui.press('1')
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-38.9, -14.6)
    pyautogui.rightClick()
    facing_trigger(-20.6, -18.2)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-55.7, -17.5)
    refreshenv()
    pyautogui.rightClick()
    facing_trigger(-90.8, -16.6)
    pyautogui.rightClick()
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-0.1, -22.9)
    pyautogui.rightClick()
    facing_trigger(-0.1, -39.4)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-179.7, 0)
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    facing_trigger(-46.2, -14)
    pyautogui.press('3')
    pyautogui.rightClick()
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(-42.2, -14.8)
    pyautogui.rightClick()
    facing_trigger(-18.3, -18.8)
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-59, -21.1)
    pyautogui.rightClick()
    facing_trigger(-90.2, -20.2)
    pyautogui.rightClick()
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(0.6, -24.2)
    pyautogui.rightClick()
    facing_trigger(-5.4, -44.9)
    pyautogui.press('3')
    pyautogui.rightClick()
    facing_trigger(-45, 0)
    pyautogui.keyDown('w')
    time.sleep(4)
    pyautogui.keyUp('w')
    facing_trigger(90.9, 23)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    facing_trigger(90.9, 44.6)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-124.7, 24.1)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-140.1, 28.5)
    pyautogui.rightClick()
    facing_trigger(-118.7, 21.7)
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-103.2, 17.7)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-114.5, 27.6)
    pyautogui.rightClick()
    facing_trigger(180, 22.9)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    facing_trigger(180, 35.1)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(27, 25.4)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(42.6, 25.2)
    pyautogui.rightClick()
    facing_trigger(15.8, 25.2)
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-1, 27.5)
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-121, 25.7)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-137.5, 30.3)
    pyautogui.rightClick()
    facing_trigger(-114, 20.3)
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-89.1, 26.7)
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-179.1, 30)
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(1.7)
    pyautogui.keyUp('w')
    pyautogui.keyDown('w')
    pyautogui.keyDown('d')
    time.sleep(1)
    pyautogui.keyUp('w')
    pyautogui.keyUp('d')
    facing_trigger(-179.1, 38.9)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-136.2, 24.5)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-153.1, 23.1)
    pyautogui.rightClick()
    facing_trigger(-133.8, 18.8)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-141.4, 21.5)
    pyautogui.rightClick()
    facing_trigger(-117.9, 17.7)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-130,29.4)
    pyautogui.rightClick()
    facing_trigger(142.7, 24.8)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(122, 25.8)
    pyautogui.rightClick()
    refreshenv()
    facing_trigger(147.9, 21.3)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(135.6, 27)
    pyautogui.rightClick()
    facing_trigger(163.8, 23.1)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(159.8, 32.4)
    pyautogui.rightClick()
    facing_trigger(90, 27.8)
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(1.7)
    pyautogui.keyUp('w')
    pyautogui.keyDown('w')
    pyautogui.keyDown('d')
    time.sleep(1)
    pyautogui.keyUp('w')
    pyautogui.keyUp('d')
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(135, 22.9)
    pyautogui.press('2')
    pyautogui.rightClick()
    facing_trigger(117.8, 25.6)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(140.3, 20.3)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(127.5, 23.6)
    pyautogui.rightClick()
    facing_trigger(152.8, 17.2)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(142.7, 24.4)
    pyautogui.rightClick()
    facing_trigger(49.8, 23)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(35.4, 31.9)
    pyautogui.rightClick()
    facing_trigger(59.7, 25.9)
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(75.9, 19.7)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(68.1, 33.2)
    pyautogui.rightClick()
    facing_trigger(0.1, 0.1)
    pyautogui.keyDown('w')
    time.sleep(1.7)
    pyautogui.keyUp('w')
    pyautogui.keyDown('w')
    pyautogui.keyDown('d')
    time.sleep(1)
    pyautogui.keyUp('w')
    pyautogui.keyUp('d')
    facing_trigger(44.9, 23.8)
    pyautogui.press('2')
    pyautogui.rightClick()
    facing_trigger(27.5, 26.6)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(47.9, 21.6)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(34.7, 22)
    pyautogui.rightClick()
    facing_trigger(64.1, 16.9)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(60.5, 28.8)
    pyautogui.rightClick()
    facing_trigger(31.7, 11.8)
    kabakk()
    facing_trigger(57.1, 11.2)
    karpuzz()
    facing_trigger(26, 18.6)
    karpuzz()
    facing_trigger(65.6, 18.3)
    kabakk()
    facing_trigger(-1.9, 13.6)
    kabakk()
    facing_trigger(-37.3, 10.5)
    kabakk()
    facing_trigger(-34.9, 16.5)
    karpuzz()
    facing_trigger(-71.3, 17.2)
    kabakk()
    facing_trigger(-12.1, 42.3)
    kabakk()
    facing_trigger(91.6, 12.8)
    karpuzz()
    facing_trigger(126.2, 10.1)
    karpuzz()
    facing_trigger(120.5, 17.1)
    kabakk()
    facing_trigger(157.1, 15.5)
    karpuzz()
    facing_trigger(89.9, 37.2)
    karpuzz()
    facing_trigger(179.7, 1.2)
    pyautogui.keyDown('w')
    time.sleep(1.3)
    pyautogui.keyUp('w')
    pyautogui.keyDown('w')
    pyautogui.keyDown('a')
    time.sleep(1)
    pyautogui.keyUp('w')
    pyautogui.keyUp('a')
    facing_trigger(121.2, 11.9)
    karpuzz()
    facing_trigger(146.7, 11.3)
    kabakk()
    facing_trigger(113.9, 19.1)
    kabakk()
    facing_trigger(156.8, 19.7)
    karpuzz()
    facing_trigger(-144, 11.4)
    kabakk()
    facing_trigger(179.6, 13.1)
    kabakk()
    facing_trigger(-146.4, 17.4)
    karpuzz()
    facing_trigger(-110.1, 17)
    kabakk()
    facing_trigger(178.8, 39.9)
    kabakk()
    facing_trigger(-90.4, 1.5)
    pyautogui.keyDown('w')
    time.sleep(1.3)
    pyautogui.keyUp('w')
    pyautogui.keyDown('w')
    pyautogui.keyDown('a')
    time.sleep(1)
    pyautogui.keyUp('w')
    pyautogui.keyUp('a')
    facing_trigger(-125.5, 11.1)
    karpuzz()
    facing_trigger(-150.2, 12)
    kabakk()
    facing_trigger(-161.3, 20.3)
    karpuzz()
    facing_trigger(-116.2, 20.7)
    kabakk()
    facing_trigger(-0.1, 0.5)
    pyautogui.keyDown('w')
    time.sleep(1.3)
    pyautogui.keyUp('w')
    pyautogui.keyDown('w')
    pyautogui.keyDown('a')
    time.sleep(1)
    pyautogui.keyUp('w')
    pyautogui.keyUp('a')
    facing_trigger(-128.2, 11.4)
    karpuzz()
    facing_trigger(-95, 13.8)
    karpuzz()
    facing_trigger(-59.6, 12.3)
    karpuzz()
    facing_trigger(-35, 11.7)
    kabakk()
    facing_trigger(-68, 19.4)
    kabakk()
    facing_trigger(-127.6, 18.8)
    kabakk()
    facing_trigger(-26.8, 18.6)
    karpuzz()
    facing_trigger(-161.5, 15.5)
    karpuzz()
    facing_trigger(-90.5, 40)
    karpuzz()
    pyautogui.press('2')
    facing_trigger(134.8, 26.4)
    pyautogui.rightClick()
    facing_trigger(110.9, 33.5)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(160.3, 34.1)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(135.1, 23.3)
    pyautogui.keyDown('w')
    time.sleep(1)
    pyautogui.keyUp('w')
    facing_trigger(-61.7, 40.4)
    pyautogui.rightClick()
    pyautogui.rightClick()
    facing_trigger(-37.4, 42.3)
    pyautogui.rightClick()
    facing_trigger(-179.6, 36.9)
    karpuzz()
    facing_trigger(0.4, 29.6)
    karpuzz()
    facing_trigger(-90.4, 29.1)
    kabakk()
    facing_trigger(89.9, 33.8)
    kabakk()
    facing_trigger(-0.1, -90)
    pyautogui.mouseDown()
    time.sleep(3)
    pyautogui.mouseUp()
    facing_trigger(-0.1, 90)
    pyautogui.press('2')
    refreshenv()
    pyautogui.keyDown("space")  # Space tuşuna basılı tut
    time.sleep(0.2)  # 0.2 saniye basılı tutsun
    pyautogui.keyUp("space")
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.keyDown("space")  # Space tuşuna basılı tut
    time.sleep(0.2)  # 0.2 saniye basılı tutsun
    pyautogui.keyUp("space")
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.keyDown("space")  # Space tuşuna basılı tut
    time.sleep(0.2)  # 0.2 saniye basılı tutsun
    pyautogui.keyUp("space")
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.keyDown("space")  # Space tuşuna basılı tut
    time.sleep(0.2)  # 0.2 saniye basılı tutsun
    pyautogui.keyUp("space")
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.keyDown("space")  # Space tuşuna basılı tut
    time.sleep(0.2)  # 0.2 saniye basılı tutsun
    pyautogui.keyUp("space")
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.rightClick()
    pyautogui.keyDown("s") 
    pyautogui.keyDown("shift")
    time.sleep(0.1)  # 0.2 saniye basılı tutsun
    pyautogui.keyUp("s")
    time.sleep(0.5)
    pyautogui.keyUp("shift")
    facing_trigger(-0.8, 80.4)
    pyautogui.press('9')
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.click()
    facing_trigger(-0.8, 76.3)
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    pyautogui.click()
    time.sleep(0.5)
    facing_trigger(-0.2, 61)
    pyautogui.press('1')
    pyautogui.rightClick()
    facing_trigger(0.2, 42.6)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(90.3, 24.1)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(1.3)
    pyautogui.keyUp('w')
    facing_trigger(90.5, 39.9)
    pyautogui.press('9')
    pyautogui.click()
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(0.7)
    pyautogui.keyUp('w')
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(-0.8, 23.8)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(1.3)
    pyautogui.keyUp('w')
    facing_trigger(-3.5, 41.5)
    pyautogui.press('9')
    pyautogui.click()
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    time.sleep(1.3)
    pyautogui.keyUp('w')
    facing_trigger(90.8, 64.6)
    pyautogui.press('2')
    pyautogui.rightClick()
    pyautogui.keyDown('w')
    pyautogui.keyDown('a')
    time.sleep(1.3)
    pyautogui.keyUp('w')
    pyautogui.keyUp('a')
    facing_trigger(-1.9, 49.3)
    pyautogui.press('9')
    pyautogui.click()
    facing_trigger(91.7, 45.5)
    pyautogui.press('9')
    pyautogui.click()
    refreshenv()


bot()
bot()
bot()
bot()
bot()
